version: '3'

networks:
  local:
    driver: bridge

services:
  backend-php:
    build:
      context: ./
      dockerfile: devops/backend-php/Dockerfile
      args:
        WWWUSER: '${WWWUSER}'
        WWWGROUP: '${WWWGROUP}'
        WWWUID: '${WWWUID}'
    volumes:
      - ./src/backend:/var/www/html
      - ./devops/backend-php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./devops/backend-php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    image: haiilo-backend-php
    container_name: haiilo-backend-php
    restart: unless-stopped
    networks:
      - local

volumes:
    mysql:
        driver: local
